### ISSUE TITLE
is_enabled返回不对

### ISSUE THREAD

**Issue by eastonliu** [SeldomQA/poium#15]
源码中第445行：
def is_enabled(self):
        """Returns whether the element is enabled."""
        elem = self.__get_element(self.k, self.v)
        return elem.is_selected()
返回错误，返回写成 return elem.is_selected()  应该是 return elem.is_enabled()

**Comment by klookAppTest** [comment]
已修复：https://github.com/SeldomQA/poium/commit/8e5fc5d6a549ec4008fe1f570a968b38b0de4b20
