### ISSUE TITLE
脚本运行会报错

### ISSUE THREAD

**Issue by liuchangfu** [SeldomQA/poium#6]
虫师大大，我照着你的例子用这个库，在运行时，老是提示“2019-09-02 18:04:35,879 - INFO - timeout 1 times, element not found!”，每一步之间，需要加个等待时间，才能找到对应元素。

**Comment by klookAppTest** [comment]
不是错误，是我加的logging，默认会循环查找你要定位的元素，每次循环查找不到就会有这个信息。默认超过5次，抛异常。
